// <auto-generated />
using HydrusTagger.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydrusTagger.Core.Data.Migrations
{
    [DbContext(typeof(TaggerDbContext))]
    [Migration("20260810224658_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HydrusTagger.Core.Data.DataDir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.ToTable("data_dirs", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.FileRecord", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DataDirId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_dir_id");

                    b.Property<int>("DataParserVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("data_parser_version");

                    b.Property<string>("FileExt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_ext");

                    b.Property<int>("FileParserVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("file_parser_version");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("ParsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_at");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.HasKey("FileId");

                    b.HasAlternateKey("Hash");

                    b.HasIndex("DataDirId")
                        .HasDatabaseName("idx_files_data_dir_id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("idx_files_hash");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.HashTag", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.HasKey("FileId", "Tag");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_hash_tags_file_id");

                    b.ToTable("hash_tags", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.HydrusMetaRecord", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<bool>("HasHumanReadableEmbeddedMetadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("has_human_readable_embedded_metadata");

                    b.Property<bool>("HasTransparency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("has_transparency");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("FileId");

                    b.ToTable("hydrus_meta", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.ItxtChunk", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<int?>("CompressionFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_flag");

                    b.Property<int?>("CompressionMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_method");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Keyword")
                        .HasColumnType("TEXT")
                        .HasColumnName("keyword");

                    b.Property<string>("LanguageTag")
                        .HasColumnType("TEXT")
                        .HasColumnName("language_tag");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("TranslatedKeyword")
                        .HasColumnType("TEXT")
                        .HasColumnName("translated_keyword");

                    b.HasKey("FileId", "Seq");

                    b.ToTable("itxt_chunks", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.LegacySchemaMigration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AppliedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("schema_migrations", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.PushRecord", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<string>("FirstPushed")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_pushed");

                    b.Property<string>("LastPushed")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_pushed");

                    b.Property<string>("TagHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_hash");

                    b.HasKey("FileId");

                    b.ToTable("pushes", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.TagMapping", b =>
                {
                    b.Property<string>("Parent")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent");

                    b.Property<string>("Child")
                        .HasColumnType("TEXT")
                        .HasColumnName("child");

                    b.HasKey("Parent", "Child");

                    b.ToTable("tag_mappings", (string)null);
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.FileRecord", b =>
                {
                    b.HasOne("HydrusTagger.Core.Data.DataDir", "DataDir")
                        .WithMany("Files")
                        .HasForeignKey("DataDirId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataDir");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.HashTag", b =>
                {
                    b.HasOne("HydrusTagger.Core.Data.FileRecord", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.HydrusMetaRecord", b =>
                {
                    b.HasOne("HydrusTagger.Core.Data.FileRecord", "File")
                        .WithOne()
                        .HasForeignKey("HydrusTagger.Core.Data.HydrusMetaRecord", "FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.ItxtChunk", b =>
                {
                    b.HasOne("HydrusTagger.Core.Data.FileRecord", "File")
                        .WithMany("ItxtChunks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.PushRecord", b =>
                {
                    b.HasOne("HydrusTagger.Core.Data.FileRecord", "File")
                        .WithOne()
                        .HasForeignKey("HydrusTagger.Core.Data.PushRecord", "FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.DataDir", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("HydrusTagger.Core.Data.FileRecord", b =>
                {
                    b.Navigation("ItxtChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
