<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hydrus-tagger</AssemblyName>
    <RootNamespace>HydrusTagger.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HydrusTagger.Core\HydrusTagger.Core.csproj" />
    <ProjectReference Include="..\HydrusTagger.Taggers\HydrusTagger.Taggers.csproj" />
  </ItemGroup>

</Project>
